- name: finding the user exists or not 
  hosts: local
  become: yes
  tasks:
    - name: sending the output to the variable using register 
      ansible.builtin.command: id expense
      ignore_errors: true
      register: user
    
    - name: printing the id expense output
      ansible.builtin.debug:
        msg: " {{ user }} "
    - name: creating the expense user
      ansible.builtin.command: useradd expense
      register: user1
    - name: printing the output of the user created or not
      ansible.builtin.debug:
        msg: "{{ user1 }}"
