# advanced method
- name: installing the packages using the loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: installing packages
      ansible.builtin.package:
        name: " {{ item.name }} "
        state: " {{ item.state }} "
      loop:
      - { name: ' mysql ' , state: ' absent' }
      - { name: ' mysql ' , state: ' present ' }
      - { name: ' postfix ' , state: ' absent ' }
