- name: installing the packages using the loops
  hosts: local
  connection: local
  tasks:
    - name: installing packages
      ansible.buitin.package:
        name: " {{ item }} "
        state: present
      loop:
      - mysql
      - nginx
      - postfix