- name: loops
  hosts: local
  connection: local
  tasks:
    - name: using the loops
      ansible.builtin.debug:
        msg: "hi {{ item }} bro!!"   # here item is a reserve keyword
      loop:
      - ajay
      - gowtham
      - srikanth
      - adi
      - vasanth