# this is a sample playbook 
# this is the play-1

- name: this is a sample play-book
  hosts: ding
  tasks:
  - name: sample task 1   
    ansible.builtin.debug:
     msg: "hi broooooooooo!!!"

# this is the play-2 
- name: play-2
  hosts: ding
  tasks:
  - name: this is the play 2 task1
    ansible.builtin.debug:
      msg: "I'm play 2 task 1"
  - name: this is the play 2 task2 
    ansible.builtin.debug:
      msg: "I'm the play 2 task2"